name: Testing github workflows
on: push
jobs:
  init:
    runs-on: dabs-runner
    env:
      STEP: "workflow - Initialisation"
      
    steps:
      - run: echo "${{vars.VAR}}}"
      - run: echo %HOSTNAME%